/*
 * DlgProyectos.java
 * Creada el 13/05/2020
 */
package UI;

import Control.Control;
import Entidades.Ciclo;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.KeyEvent;
import Entidades.Encargado;
import Entidades.Equipo;
import Entidades.Proyecto;
//import javax.swing.DefaultComboBoxModel;

/**
 * Esta clase es una ventana de dialogo que muestra sus funciones segun la
 * opcion seleccionada.
 *
 * @author Jesús González
 */
public class DlgProyectos extends javax.swing.JDialog {

    /**
     * Ventana de dialogo para la operación seleccionada a realizar en un
     * turista
     *
     * @param parent Ventana sobre la que aparecerá el cuadro de diálogo
     * @param title Título del cuadro de diálogo
     * @param modal true si permite acceder fuera de los límites del cuadro de
     * diálogo, false en caso contrario
     * @param alumno Alumno a agregar, editar o eliminar
     * @param operacion Operación a realizar en el cuadro de diálogo: AGREGAR =
     * 0, ACTUALIZAR = 1, ELIMINAR = 2, DESPLEGAR = 3;
     * @param respuesta Boton presionado al salir de los cuadros de * diálogos:
     * ACEPTAR = "Aceptar", CANCELAR = "Cancelar".
     */
    public DlgProyectos(java.awt.Frame parent, String title, boolean modal, Proyecto proyecto, int operacion, StringBuffer respuesta) {//Poner el combox en el parametro tambn
        super(parent, title, modal);
        initComponents();
        this.proyecto = proyecto;
        this.operacion = operacion;
        this.respuesta = respuesta;
        //this.listaTuristas = listaTuristas;

        if (operacion == ConstantesGUI.AGREGAR) {
            botonAceptar.setText("Guardar");
        } else if (operacion == ConstantesGUI.ACTUALIZAR) {
            botonAceptar.setText("Actualizar");
        } else if (operacion == ConstantesGUI.ELIMINAR) {
            botonAceptar.setText("Eliminar");
            botonRetaurar.setEnabled(false);
        } else if (operacion == ConstantesGUI.DESPLEGAR) {
            botonAceptar.setText("Continuar");
            botonRetaurar.setEnabled(false);
            botonCancelar.setEnabled(false);
        }
        
        tf_idproyecto.setText(String.valueOf(proyecto.getIDProyecto()));
        
        if (operacion == ConstantesGUI.ELIMINAR || operacion == ConstantesGUI.ACTUALIZAR
                || operacion == ConstantesGUI.DESPLEGAR) {
            tf_idproyecto.setText(String.valueOf(proyecto.getIDProyecto()));
            tf_nombrePro.setText(proyecto.getNombredelProyecto());
            tf_descripcion.setText(proyecto.getDescripcion());
            tf_equipo.setText(String.valueOf(proyecto.getIDEquipo().getIDEquipo()));
            tf_encargado.setText(String.valueOf(proyecto.getIDEncargado().getIDEncargado()));
            tf_ciclo.setText(String.valueOf(proyecto.getIDCiclo().getIDCiclo()));
//            cb_ciclos.setSelectedItem(proyecto.getIDCiclo().getCiclo());
//            cb_cicloanio.setSelectedItem(proyecto.getIDCiclo().getAnio());
        }
        
        if (operacion == ConstantesGUI.ELIMINAR || operacion == ConstantesGUI.DESPLEGAR) {
            tf_idproyecto.setEditable(false);
            tf_nombrePro.setEditable(false);
            tf_descripcion.setEditable(false);
            tf_equipo.setEditable(false);
            tf_ciclo.setEditable(false);
//            cb_ciclos.setEditable(false);
//            cb_cicloanio.setEditable(false);
        }
        
        if (operacion == ConstantesGUI.AGREGAR) {
            tf_idproyecto.setEditable(false);
        }
        
        respuesta.append(ConstantesGUI.CANCELAR);
        
        centraCuadroDialogo(parent);
        
        setVisible(true);
    }
    
    public void centraCuadroDialogo(java.awt.Frame parent) {
        Dimension frameSize = parent.getSize();
        Point loc = parent.getLocation();
        Dimension dlgSize = getPreferredSize();
        setLocation((frameSize.width - dlgSize.width) / 2 + loc.x, (frameSize.height - dlgSize.height) / 2 + loc.y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tf_idproyecto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_nombrePro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        botonRetaurar = new javax.swing.JButton();
        tf_descripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_equipo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_encargado = new javax.swing.JTextField();
        tf_ciclo = new javax.swing.JTextField();

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Año:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Proyecto ID:");

        tf_idproyecto.setColumns(15);
        tf_idproyecto.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nombre del proyecto:");

        tf_nombrePro.setColumns(20);
        tf_nombrePro.setToolTipText("Nombre del cliente");
        tf_nombrePro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_nombreProKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Descripción:");

        botonAceptar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botonAceptar.setText("Aceptar");
        botonAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonRetaurar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botonRetaurar.setText("Restaurar");
        botonRetaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRetaurarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Equipo ID:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Encargado ID:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Ciclo ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tf_descripcion)
                        .addComponent(tf_nombrePro, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                        .addComponent(tf_encargado, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_idproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tf_ciclo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(botonAceptar)
                .addGap(33, 33, 33)
                .addComponent(botonRetaurar)
                .addGap(35, 35, 35)
                .addComponent(botonCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(tf_idproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_nombrePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_equipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_encargado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_ciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRetaurar)
                    .addComponent(botonCancelar)
                    .addComponent(botonAceptar))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonRetaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRetaurarActionPerformed
        if (operacion == ConstantesGUI.AGREGAR) {
            //campoTextoCurp.setText("");
            tf_nombrePro.setText("");
            tf_descripcion.setText("");
            tf_equipo.setText("");
            tf_encargado.setText("");
            tf_ciclo.setText("");
//            cb_ciclos.setSelectedIndex(0);
//            cb_cicloanio.setSelectedIndex(0);
        }
        
        if (operacion == ConstantesGUI.ACTUALIZAR) {
            tf_idproyecto.setText(String.valueOf(proyecto.getIDProyecto()));
            tf_nombrePro.setText(proyecto.getNombredelProyecto());
            tf_descripcion.setText(proyecto.getDescripcion());
            tf_equipo.setText(String.valueOf(proyecto.getIDEquipo().getIDEquipo()));
            tf_encargado.setText(String.valueOf(proyecto.getIDEncargado().getIDEncargado()));
            tf_ciclo.setText(String.valueOf(proyecto.getIDCiclo().getIDCiclo()));
//            cb_ciclos.setSelectedItem(proyecto.getIDCiclo().getCiclo());
//            cb_cicloanio.setSelectedItem(proyecto.getIDCiclo().getAnio());
        }
    }//GEN-LAST:event_botonRetaurarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        if ((operacion == ConstantesGUI.AGREGAR) || operacion == ConstantesGUI.ACTUALIZAR) {
            proyecto.setIDProyecto(Integer.parseInt(tf_idproyecto.getText()));
            proyecto.setNombredelProyecto(tf_nombrePro.getText());
            proyecto.setDescripcion(tf_descripcion.getText());
            proyecto.setIDEncargado(new Encargado(Integer.parseInt(tf_encargado.getText())));
            proyecto.setIDEquipo(new Equipo(Integer.parseInt(tf_equipo.getText())));
            //proyecto.setIDCiclo(iDCiclo);
            proyecto.setIDCiclo(new Ciclo(Integer.parseInt(tf_ciclo.getText())));
        }
        respuesta.delete(0, respuesta.length());
        respuesta.append(ConstantesGUI.ACEPTAR);
        this.dispose();
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void tf_nombreProKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nombreProKeyTyped
        
        char c = evt.getKeyChar();
        int k = (int) evt.getKeyChar();
        if (!Character.isLetter(c) && c != KeyEvent.VK_SPACE) {
            evt.consume();
        }
//
//        if (Character.isDigit(c)) {
//            getToolkit().beep();
//            evt.consume();
//            JOptionPane.showMessageDialog(rootPane, "Ingresar solo letras ");
//        }        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombreProKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonRetaurar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tf_ciclo;
    private javax.swing.JTextField tf_descripcion;
    private javax.swing.JTextField tf_encargado;
    private javax.swing.JTextField tf_equipo;
    private javax.swing.JTextField tf_idproyecto;
    private javax.swing.JTextField tf_nombrePro;
    // End of variables declaration//GEN-END:variables
    private Proyecto proyecto;
    private int operacion;
    private StringBuffer respuesta;
    private Control con;
}
