/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Control.Control;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Jesus
 */
public class HomeTablaGanadora extends javax.swing.JFrame {

    /**
     * Creates new form Homr
     */
    public HomeTablaGanadora() {
        initComponents();
        centraVentana();
    }

    /**
     * Este método centra la ventana de la aplicación sobre la pantalla.
     */
    private void centraVentana() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        setLocation((screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        m_proyecto = new javax.swing.JMenu();
        im_agregarPro = new javax.swing.JMenuItem();
        im_actualizarPro = new javax.swing.JMenuItem();
        im_eliminarPro = new javax.swing.JMenuItem();
        m_alumno = new javax.swing.JMenu();
        im_agregarAlu = new javax.swing.JMenuItem();
        im_actualizarAlu = new javax.swing.JMenuItem();
        im_eliminarAlu = new javax.swing.JMenuItem();
        m_encargado = new javax.swing.JMenu();
        im_agregarEnc = new javax.swing.JMenuItem();
        im_actualizarEnc = new javax.swing.JMenuItem();
        im_eliminarEnc = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        im_tProyectos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Administrar");

        m_proyecto.setText("Proyecto");

        im_agregarPro.setText("Agregar");
        im_agregarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im_agregarProActionPerformed(evt);
            }
        });
        m_proyecto.add(im_agregarPro);

        im_actualizarPro.setText("Actualizar");
        im_actualizarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im_actualizarProActionPerformed(evt);
            }
        });
        m_proyecto.add(im_actualizarPro);

        im_eliminarPro.setText("Eliminar");
        im_eliminarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im_eliminarProActionPerformed(evt);
            }
        });
        m_proyecto.add(im_eliminarPro);

        jMenu1.add(m_proyecto);

        m_alumno.setText("Alumno");

        im_agregarAlu.setText("Agregar");
        im_agregarAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im_agregarAluActionPerformed(evt);
            }
        });
        m_alumno.add(im_agregarAlu);

        im_actualizarAlu.setText("Actualizar");
        im_actualizarAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im_actualizarAluActionPerformed(evt);
            }
        });
        m_alumno.add(im_actualizarAlu);

        im_eliminarAlu.setText("Eliminar");
        im_eliminarAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im_eliminarAluActionPerformed(evt);
            }
        });
        m_alumno.add(im_eliminarAlu);

        jMenu1.add(m_alumno);

        m_encargado.setText("Encargado");

        im_agregarEnc.setText("Agregar");
        im_agregarEnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im_agregarEncActionPerformed(evt);
            }
        });
        m_encargado.add(im_agregarEnc);

        im_actualizarEnc.setText("Actualizar");
        im_actualizarEnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im_actualizarEncActionPerformed(evt);
            }
        });
        m_encargado.add(im_actualizarEnc);

        im_eliminarEnc.setText("Eliminar");
        im_eliminarEnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im_eliminarEncActionPerformed(evt);
            }
        });
        m_encargado.add(im_eliminarEnc);

        jMenu1.add(m_encargado);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultar");

        im_tProyectos.setText("Tabla de proyectos");
        im_tProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im_tProyectosActionPerformed(evt);
            }
        });
        jMenu2.add(im_tProyectos);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void im_eliminarAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im_eliminarAluActionPerformed
        control.elminarAlumno(this);
    }//GEN-LAST:event_im_eliminarAluActionPerformed

    private void im_agregarAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im_agregarAluActionPerformed
        control.agregaAlumno(this);
    }//GEN-LAST:event_im_agregarAluActionPerformed

    private void im_actualizarAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im_actualizarAluActionPerformed
        control.actualizaAlumno(this);
    }//GEN-LAST:event_im_actualizarAluActionPerformed

    private void im_agregarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im_agregarProActionPerformed
        control.agregarProyecto(this);
    }//GEN-LAST:event_im_agregarProActionPerformed

    private void im_agregarEncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im_agregarEncActionPerformed
        control.agregaEncargado(this);
    }//GEN-LAST:event_im_agregarEncActionPerformed

    private void im_actualizarEncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im_actualizarEncActionPerformed
        control.actualizaEncargado(this);
    }//GEN-LAST:event_im_actualizarEncActionPerformed

    private void im_eliminarEncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im_eliminarEncActionPerformed
        control.eliminarEncargado(this);
    }//GEN-LAST:event_im_eliminarEncActionPerformed

    private void im_actualizarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im_actualizarProActionPerformed
        control.actualizarProyecto(this);
    }//GEN-LAST:event_im_actualizarProActionPerformed

    private void im_eliminarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im_eliminarProActionPerformed
        control.eliminarProyecto(this);
    }//GEN-LAST:event_im_eliminarProActionPerformed

    private void im_tProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im_tProyectosActionPerformed
        DlgTabla tavla = new DlgTabla(this, "Tabla proyectos", true);
    }//GEN-LAST:event_im_tProyectosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeTablaGanadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeTablaGanadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeTablaGanadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeTablaGanadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeTablaGanadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem im_actualizarAlu;
    private javax.swing.JMenuItem im_actualizarEnc;
    private javax.swing.JMenuItem im_actualizarPro;
    private javax.swing.JMenuItem im_agregarAlu;
    private javax.swing.JMenuItem im_agregarEnc;
    private javax.swing.JMenuItem im_agregarPro;
    private javax.swing.JMenuItem im_eliminarAlu;
    private javax.swing.JMenuItem im_eliminarEnc;
    private javax.swing.JMenuItem im_eliminarPro;
    private javax.swing.JMenuItem im_tProyectos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu m_alumno;
    private javax.swing.JMenu m_encargado;
    private javax.swing.JMenu m_proyecto;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JTable jtabla;
    Control control = new Control();
}
